### ISSUE TITLE
Add support for showing announcements

### ISSUE THREAD

**Issue by gustavcorpas** [atjn/simple-moodle#2]
When visiting a course page Moodle can have important messages from teachers. These are found under announcements. However the format does not seem to be standardized. I have seen course-pages have a link to an announcements page, and course-pages that show recent announcements in a side panel.

Ideally I would like a collapsable panel that show the most recent announcements when visiting a given course.

**Comment by atjn** [comment]
I believe this is fixed in v2, as announcements are now part of a side pane that is not removed.
